#!/bin/sh
#
# Hacked script to run automagically run tmux on a remote host
#
if [ "X$1" = "X" ]; then
	echo "usage: `basename $0` <host>"
	exit 1
fi

if [ "X$SSH_AUTH_SOCK" = "X" ]; then
    # no ssh-agent, game over.
    echo "No ssh-agent running, continuing anyway...."
fi

#AUTOSSH_POLL=600
AUTOSSH_PORT=0
#AUTOSSH_GATETIME=30
#AUTOSSH_LOGFILE=$HOST.log
#AUTOSSH_DEBUG=yes 
#AUTOSSH_PATH=`whereis ssh`
export AUTOSSH_POLL AUTOSSH_LOGFILE AUTOSSH_DEBUG AUTOSSH_PATH AUTOSSH_GATETIME AUTOSSH_PORT

#exec autossh -A -t $1 "screen -D -R"
exec autossh -A -t $1 "tmux has && tmux attach -d || tmux new"
